### ISSUE TITLE
Support for 3.12

### ISSUE THREAD

**Issue by vinodronold** [TUV-SUD-Product-Service-GmbH/QuteStyle#103]
**Is your feature request related to a problem? Unable to use with Python 3.12
Is there a plan to add support for 3.12?

**Comment by p5k369** [comment]
Hey @vinodronold, 
thank you for your suggestion. Find the latest version which includes python 3.12 support here:
https://github.com/TUV-SUD-Product-Service-GmbH/QuteStyle/releases/tag/v1.0.8
