### ISSUE TITLE
add additional icons in checkable combox AB#74508

### ISSUE THREAD

**Issue by p5k369** [TUV-SUD-Product-Service-GmbH/QuteStyle#26]
An icon should be displayed between checkbox and text if needed. 
![image](https://user-images.githubusercontent.com/75496702/164421771-afc113f7-ab8d-4665-88fc-39f2172dae8d.png)

**Comment by p5k369** [comment]
Hey @TilmanK do you think you can reimplement this feature?

**Comment by TilmanK** [comment]
> Hey @TilmanK do you think you can reimplement this feature?

Guess this is easy. Scale the icon to the height of the checkbox and take the relevant space from the text's QRect.

Something you need to keep in mind is that the sizeHint might need some tweaking, as truncating the icon will for sure look ugly.

I'll take a look…

**Comment by TilmanK** [comment]
Fixed with #29

**Comment by p5k369** [comment]
Fixed in #29 as mentioned in comment of @TilmanK
